
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.rTree;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIPE = 8;
  public static final int DOUBLE_COLON = 6;
  public static final int EOF = 0;
  public static final int RIGHT_BRACKET = 3;
  public static final int error = 1;
  public static final int DATO = 9;
  public static final int RIGHT_BRACE = 5;
  public static final int IDENTIFIER = 7;
  public static final int LEFT_BRACKET = 2;
  public static final int LEFT_BRACE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LEFT_BRACKET",
  "RIGHT_BRACKET",
  "LEFT_BRACE",
  "RIGHT_BRACE",
  "DOUBLE_COLON",
  "IDENTIFIER",
  "PIPE",
  "DATO"
  };
}

